### ISSUE TITLE
main.py showing error

### ISSUE THREAD

**Issue by Ayush1285** [fdcl-gwu/uav_simulator#1]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ayush/uav_simulator/scripts/thread_control.py", line 33, in thread_control
    fM = rover.run_controller()
  File "/home/ayush/uav_simulator/scripts/rover.py", line 86, in run_controller
    fM = self.control.run(states, desired)
  File "/home/ayush/uav_simulator/scripts/control.py", line 227, in run
LOG: thread starting ..
    self.position_control()
  File "/home/ayush/uav_simulator/scripts/control.py", line 311, in position_control
    b3c, b3c_dot, b3c_2dot = deriv_unit_vector(-A, -A_dot, -A_2dot)
  File "/home/ayush/uav_simulator/scripts/matrix_utils.py", line 83, in deriv_unit_vector
    - A.dot(A_dot.dot(A_dot) + A.dot(A_2dot)) / nA3 \
ValueError: shapes (3,) and (1,) not aligned: 3 (dim 0) != 1 (dim 0)

**Comment by kanishkegb** [comment]
Can you try commenting out line 14 in [matrix_utils.py](https://github.com/fdcl-gwu/uav_simulator/blob/c713e3ee377496e7334651ec5f1b1ff523e5be85/scripts/matrix_utils.py#L14)?

**Comment by Ayush1285** [comment]
> Can you try commenting out line 14 in [matrix_utils.py](https://github.com/fdcl-gwu/uav_simulator/blob/c713e3ee377496e7334651ec5f1b1ff523e5be85/scripts/matrix_utils.py#L14)?

It worked.
Thank You!!

**Comment by Ayush1285** [comment]
https://user-images.githubusercontent.com/64409716/127598577-3dcb620d-5082-40d9-b887-af597e4d7e79.mp4

It is immediately crashing into the ground plane after clicking on the take-off option.

**Comment by Ayush1285** [comment]
https://user-images.githubusercontent.com/64409716/127598577-3dcb620d-5082-40d9-b887-af597e4d7e79.mp4

It is immediately crashing into the ground plane after clicking on the take-off option.

**Comment by kanishkegb** [comment]
Does this happen every time you click on take-off button? Does it show any error messages?

**Comment by kanishkegb** [comment]
Closed due to inactivity

**Comment by tiralonghipol** [comment]
hi, I am facing a similar issue
my real-time factor never drops below 0.9, so I doubt it would be that
the controller seems unstable, should I attempt to tune the attitude gains?

**Comment by tiralonghipol** [comment]
[edit]
@kanishkegb  it works after a while, very weird
maybe some frequencies/topics have to stabilize before running the controller?

**Comment by kanishkegb** [comment]
Hi @tiralonghipol! 

Sorry, it took a while to respond. I am not sure about an immediate solution without any further data. Are you running this on a virtual machine? Does your real-time factor starts low and then slowly goes towards 1.0?

**Comment by tiralonghipol** [comment]
Im built everything from source, ubuntu20 ros noetic
I would say no, the system behaves correctly only after some time
very weird

**Comment by kanishkegb** [comment]
Unfortunately, it is really hard for me to find a possible fix since I cannot replicate the issue. This seems to be a problem that is not just limited to you (as evident by the other few people in this issue). I have tried in multiple computers, but never got to replicate this. If you find any fix or a clue, please send it this way.
