### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by tiralonghipol** [fdcl-gwu/uav_simulator#10]
thank you for your very nice package.
I found a small bug at [this line](https://github.com/fdcl-gwu/uav_simulator/blob/344cebf0f1947c7f0a4df69b681d24a75caaeb10/scripts/plot_utils.py#L72)

I think the legend id should be 1, otherwise the element 0 is accessed 2 times : )

**Comment by kanishkegb** [comment]
Thanks for the bug @tiralonghipol! This has been fixed in #11.
