### ISSUE TITLE
[Errno 13] Permission denied: '/home/uav_simulator/build' when trying to build using catkin_make

### ISSUE THREAD

**Issue by amarnath-asteria** [fdcl-gwu/uav_simulator#13]
![image](https://github.com/fdcl-gwu/uav_simulator/assets/107453229/85f59898-f103-4952-97ff-92fc8fbd4b5f)

I followed the instructions as given and i accessed the docker bash and tried to build using catkin_make. when i try running using sudo, it asked for the password which is not given

**Comment by kanishkegb** [comment]
What `sudo` commands are you trying inside docker? Can you show me the specific line of code that uses `sudo`?

**Comment by amarnath-asteria** [comment]
> What `sudo` commands are you trying inside docker? Can you show me the specific line of code that uses `sudo`?

I am trying to do catkin_make to build the uav_simulator

**Comment by kanishkegb** [comment]
On the screenshot, I can see you are running a `sudo` command. What command is that?

**Comment by kanishkegb** [comment]
Stale issue, closing
