### ISSUE TITLE
Quadrotor can't hover

### ISSUE THREAD

**Issue by enavid** [fdcl-gwu/uav_simulator#3]
Thanks a lot for your project.
 I build your project. when I ran 'main.py' with python3.6, project run successfully. but quadrotor can't fly correcly.

'''
[ERROR] [1654881885.678907, 1879.197000]: bad callback: <bound method Rover.ros_imu_callback of <rover.Rover object at 0x7fb62ac620f0>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/navid/Desktop/uav_simulator/scripts/rover.py", line 110, in ros_imu_callback
    self.estimator.imu_correction(R_fi, self.V_R_imu)
  File "/home/navid/Desktop/uav_simulator/scripts/estimator.py", line 156, in imu_correction
    del_z = 0.5 * vee(imu_R - imu_R.T)
  File "/home/navid/Desktop/uav_simulator/scripts/matrix_utils.py", line 34, in vee
    ensure_skew(x, 3)
  File "/home/navid/Desktop/uav_simulator/scripts/matrix_utils.py", line 223, in ensure_skew
    raise ValueError('Input array must be a skew-symmetric matrix')
ValueError: Input array must be a skew-symmetric matrix

'''

https://user-images.githubusercontent.com/43311646/173120485-d5543bd1-8eb0-4983-ab0c-ff28e54730f0.mp4

**Comment by kanishkegb** [comment]
Hey @TejaswiKC , is this the same issue you had?

**Comment by kanishkegb** [comment]
BTW, @enavid did you change anything in the Gazebo environment? The IMU should not be running at almost 2000 Hz (what I see on the GUI).

**Comment by TejaswiKC** [comment]
Yes @kanishkegb, this is similar to the issue that I had. If you are using ROS Melodic, it is better to run the 'main.py' with python 2.7 to avoid such errors. However, you will have to manually change the '@' operator to np.dot since it does not work in python 2.

**Comment by kanishkegb** [comment]
Closing as a stale issue.

**Comment by ah19190** [comment]
Hi there, thanks for the work you have done regarding your project. I am facing the same issue as the original post, and I saw @TejaswiKC answer and I tried to change the '@' operator, but I still get similar behaviour - I might be missing out on some changed I needed to make. 

I wanted to ask 2 things: 
-  how did you get the project to work originally as I thought you were using ROS melodic with ubuntu 18.04, which is what I have done but when using python3, it behaves like in the video of the original post? 
- if I want to change it to work with python 2, do I just edit the all the relevant python files inside script? Or is there other areas? Or let me know how I can make the original code in this repo work.

**Comment by kanishkegb** [comment]
Hi Brendan! 

I assume you run the code as `python3 main.py`?

Also, can you please provide the outputs of the following commands?

```sh
which python
python --version
python -c "import numpy; print(numpy.__version__)"

which python3
python3 --version
python3 -c "import numpy; print(numpy.__version__)"
```

**Comment by ah19190** [comment]
Hi Kanishke, 

I ran it both using ```python3 main.py``` and ```python2.7 main.py``` and both times I get the error of it crashing. 

```@ubuntu2:~$ which python
/usr/bin/python
@ubuntu2:~$ python --version
Python 2.7.17
@ubuntu2:~$ python -c "import numpy; print(numpy.__version__)"
1.16.6
@ubuntu2:~$ which python3
/usr/bin/python3
@ubuntu2:~$ python3 --version
Python 3.6.9
@ubuntu2:~$ python3 -c "import numpy; print(numpy.__version__)"
1.19.5
```

Thanks for your help!

**Comment by kanishkegb** [comment]
I will check this tonight and update back.

**Comment by kanishkegb** [comment]
Btw, while I check the full code, can you try this and see if it works?
`python3 -m pip install --force-reinstall numpy==1.22`

**Comment by ah19190** [comment]
I get an error when trying to do that. 

```
Collecting numpy==1.22
  Could not find a version that satisfies the requirement numpy==1.22 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5)
No matching distribution found for numpy==1.22
```

I think it is due to the fact that numpy support has been dropped for python version 3.6 
https://stackoverflow.com/questions/66182906/error-no-matching-distribution-found-for-numpy-when-deploying-app-to-heroku

**Comment by kanishkegb** [comment]
My bad, I think I had this run with Noetic/python3.9 at some point, and used numpy 1.22. I will check the whole thing later and update here.

**Comment by kanishkegb** [comment]
This is going to take some time for me to verify. My Ubuntu partition seem to be corrupted. I will check this probably this weekend.

**Comment by kanishkegb** [comment]
@ah19190 
Can you try this branch and report back if you have any issues? 
https://github.com/fdcl-gwu/uav_simulator/tree/ros-melodic
This has all `@` replaced with `.dot`, and seem to work for me.

**Comment by ah19190** [comment]
I have tried the branch, and unfortunately I still seem to experience the same behaviour. 

I deleted the repository and cloned it again to make sure I am using the exact same branch. I have followed the steps mentioned in the README.md and tried both ```python2.7 main.py``` and ```python3 main.py```
As soon as it launches, the quadcopter will become unbalanced and flip over to the ground. 

Can I check that you are using ubuntu 18.04, with ROS melodic? 

I am using the ```ros-melodic-desktop-full``` from http://wiki.ros.org/melodic/Installation/Ubuntu.

**Comment by kanishkegb** [comment]
Yes, I actually did a fresh install of Ubuntu 18.04 because my Ubuntu partition was corrupt, and followed all instructions in the README, with `python main.py`. Below are my system details:

```sh
lsb_release -a :                                                                 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

rosversion -d:
melodic

python --version:
Python 2.7.17

python -c "import numpy; print(numpy.__version__)":
1.13.3
```

Note that I have `numpy=1.13.3`. Maybe you can try `python -m pip install --force-reinstall numpy==1.13.3`?

1. Are you using a virtual machine to run Ubuntu? 
2. What is the real-time factor for the Gazebo sim (one on the bottom of the screen, mine is around 0.97-0.99)?
3. Does the terminal displays any errors/warning when you run `roslaunch`?

**Comment by ah19190** [comment]
Yes I checked again that I am using ```numpy=1.13.3``` and reinstalled it. Unfortunately I am still unable to get it to work even after making sure my system details are the same as yours which is strange. 

1. Yes I am using virtualbox on my macbook to run ubuntu. 
2. Real time factor is between 0.67-0.73 for the sim. 
3. No there are no warnings when I run roslaunch. 

Thanks for your continued help.

**Comment by kanishkegb** [comment]
Oh I think this makes more sense now. Running the Gazebo sim at a ~0.7 real-time factor is pretty bad. That means, when the python code is at 10 seconds, the simulation is actually at 7 seconds. So it makes sense that it cannot compensate for the attitude tilt, and flips over. 

I highly recommend running this natively on Ubuntu, or at least running this on a computer powerful enough to run the gazebo inside a virtual machine with a real-time factor closer to 1.0. 

I will add this to the readme file for future references.

**Comment by kanishkegb** [comment]
The issues with real-time factors and virtual machines was added to the readme in #5. The `main` branch now supports Ubuntu 20.04 running ROS-Noetic with Python 3.8.10. Also, a separate branch is added to for `ros-melodic` for ROS-Melodic users on Ubuntu 18.04.
