### ISSUE TITLE
PX4 work ok?

### ISSUE THREAD

**Issue by cillian-bao** [fdcl-gwu/uav_simulator#4]
This simulation platform can support the px4，I see the Wrench.msg can publish to the uav, but in the hardware experiment, the controller is PX4, the Wrench.msg can work either?

**Comment by kanishkegb** [comment]
If you want PX4 support, I highly recommend using the official repo [link](https://docs.px4.io/main/en/simulation/gazebo.html). This repo is not intended to replace that. `Wrench.msg` is just how the UAV actuation talks to the Gazebo model.
