### ISSUE TITLE
Question about the self.R_fg in rover.py

### ISSUE THREAD

**Issue by CLi-11** [fdcl-gwu/uav_simulator#7]
Hi， 

I found that the following "self.R_fg" in the "rover.py" is used to transform from ENU frame to NED frame.
  self.R_fg = np.array([
            [1.0, 0.0, 0.0],
            [0.0, -1.0, 0.0],
            [0.0, 0.0, -1.0]
        ])
However, from my understanding, the following should be used,
self.R_fg = np.array([ 
            [0.0, 1.0, 0.0],
            [1.0, 0.0, 0.0],
            [0.0, 0.0, -1.0]
        ])
am I wrong? maybe I miss something.

Thanks in advance for your help!

**Comment by kanishkegb** [comment]
Yes, you are correct in terms of what north, east actually means as directions. But what is implied and used here is that "North" of `NED` and "East" of `ENU` are the first axis. 

In other words, "North" used in our lab is the same direction as "East" used in Gazebo. I will add some comments clarifying this to the code. Thanks for bringing it to the attention.

**Comment by kanishkegb** [comment]
This has been addressed in #9.
